# refers to directory under <repo>/python-modules/<python-module>
appModule: test                                         # Application module instance name
type: python                                            # Application type
containerName: test                                     # Docker container name

cron: "15 */15 * * * *"                                 # Execution every 15 minutes on the 15th second 
logLevel: "INFO"                                        # Either text or numeric input
params:
  apiEndpoint: "http://localhost:8080/api"              # API endpoint to call
  token: "Bearer YOUR_TOKEN"                            # Authorization token (replace with real one)                 
  production_p_lt_DP_ID: "production_p_lt"              # pointer to dp
  consumption_p_lt_DP_ID: "consumption_p_lt"            # pointer to dp
  elering_nps_price_DP_ID: "elering_nps_price"          # pointer to dp
  pccImportLimitW_DP_ID: "pcc_max_import"               # pointer to dp
  pccExportLimitW_DP_ID: "pcc_max_export"               # pointer to dp 
  interval: 900                                         # constant
  DAY_TARIFF: 0.07                                      # constant
  timezone: "Europe/Tallinn"                            # constant
